<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net6.0;net8.0</TargetFrameworks>
		<ImplicitUsings>disable</ImplicitUsings>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<AppendTargetFrameworkToOutputPath>true</AppendTargetFrameworkToOutputPath>
		<RootNamespace>Keyfactor.Extensions.Orchestrator.HashicorpVault</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
	  <None Include="..\hashicorp-vault-orchestrator.sln.licenseheader" Link="hashicorp-vault-orchestrator.sln.licenseheader" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="BouncyCastle.Cryptography" Version="2.4.0" />
		<PackageReference Include="Keyfactor.Logging" Version="1.1.1" />
		<PackageReference Include="Keyfactor.Orchestrators.Common" Version="3.2.0">
		  <IncludeAssets>all</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Keyfactor.Orchestrators.IOrchestratorJobExtensions" Version="0.7.0" />
		<PackageReference Include="Keyfactor.Platform.IPAMProvider" Version="1.0.0" />
		<PackageReference Include="Microsoft.CSharp" Version="4.7.0">
		  <IncludeAssets>all</IncludeAssets>
		</PackageReference>
		<PackageReference Include="NLog" Version="5.3.4" />
		<PackageReference Include="System.Drawing.Common" Version="6.0.0" />
		<PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.0" />
		<PackageReference Include="System.Text.Json" Version="8.0.5" />
		<PackageReference Include="VaultSharp" Version="1.17.5.1">
			<IncludeAssets>all</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<None Update="manifest.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>
