# Store Type creation script using kfutil
# Generated by Doctool

Write-Host "Creating store type: HCVPKI"
kfutil store-types create HCVPKI

Write-Host "Creating store type: HCVKVPEM"
kfutil store-types create HCVKVPEM

Write-Host "Creating store type: HCVKVJKS"
kfutil store-types create HCVKVJKS

Write-Host "Creating store type: HCVKVP12"
kfutil store-types create HCVKVP12

Write-Host "Creating store type: HCVKVPFX"
kfutil store-types create HCVKVPFX

