# Store Type creation script using Invoke-RestMethod
# Generated by Doctool

# Configuration - set these variables before running
$KeyfactorHostname = $env:KEYFACTOR_HOSTNAME
$KeyfactorApiPath = if ($env:KEYFACTOR_API_PATH) { $env:KEYFACTOR_API_PATH } else { "KeyfactorAPI" }
$KeyfactorAuthToken = $env:KEYFACTOR_AUTH_TOKEN

$Headers = @{
    "Authorization" = "Bearer $KeyfactorAuthToken"
    "Content-Type" = "application/json"
    "x-keyfactor-requested-with" = "APIClient"
}

Write-Host "Creating store type: HCVPKI"
$Body = @'
{
  "Name": "Hashicorp Vault PKI",
  "ShortName": "HCVPKI",
  "Capability": "HCVPKI",
  "LocalStore": false,
  "JobProperties": [],
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "PrivateKeyAllowed": "Forbidden",
  "CustomAliasAllowed": "Forbidden",
  "StorePathType": "Fixed",
  "StorePathValue": "/",
  "SupportedOperations": {
    "Add": false,
    "Create": false,
    "Discovery": false,
    "Enrollment": false,
    "Remove": false
  },
  "Properties": [
    {
      "Name": "ServerUsername",
      "DisplayName": "Server Username",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true,
      "IsPAMEligible": true,
      "Description": "The base URI (and port) to the instance of Hashicorp Vault ex: https://localhost:8200"
    },
    {
      "Name": "ServerPassword",
      "DisplayName": "Server Password",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true,
      "IsPAMEligible": true,
      "Description": "Vault token that will be used by the Orchestrator integration for authenticating and performing operations in the Vault instance"
    },
    {
      "Name": "MountPoint",
      "DisplayName": "Mount Point",
      "Description": "This is the mount point of the instance of the PKI or Keyfactor secrets engine plugin.  If using enterprise namespaces: <namespace>/<mount point>",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true
    },
    {
      "Name": "PassphrasePath",
      "DisplayName": "Passphrase Path",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "Description": "This is the path to the secret that contains the passphrase to the cert store file.  If empty or omitted, assume the secret is named 'passphrase' on the same level as the certificate store secret."
    }
  ],
  "EntryParameters": [],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default",
    "StorePassword": {
      "Description": "Vault token that will be used for authenticating",
      "IsPAMEligible": true
    }
  }
}
'@

Invoke-RestMethod -Uri "https://$KeyfactorHostname/$KeyfactorApiPath/CertificateStoreTypes" -Method POST -Headers $Headers -Body $Body

Write-Host "Creating store type: HCVKVPEM"
$Body = @'
{
  "Name": "Hashicorp Vault Key-Value PEM",
  "ShortName": "HCVKVPEM",
  "Capability": "HCVKVPEM",
  "LocalStore": false,
  "StorePathType": "",
  "StorePathValue": "example: '/mycerts/mycert_pem?b64cert'",
  "PrivateKeyAllowed": "Optional",
  "JobProperties": [
    {
      "Name": "DiscoverySuffix",
      "DisplayName": "Discovery Suffix",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "_pem",
      "Required": false,
      "Description": "The secret-key-name suffix Discovery jobs use to identify candidate PEM certificate secrets. Defaults to '_pem'."
    }
  ],
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required",
  "SupportedOperations": {
    "Add": true,
    "Create": true,
    "Discovery": true,
    "Enrollment": false,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "ServerUsername",
      "DisplayName": "Server Username",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true,
      "IsPAMEligible": true,
      "Description": "The base URI (and port) to the instance of Hashicorp Vault ex: https://localhost:8200"
    },
    {
      "Name": "ServerPassword",
      "DisplayName": "Server Password",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true,
      "IsPAMEligible": true,
      "Description": "Vault token that will be used by the Orchestrator integration for authenticating and performing operations in the Vault instance"
    },
    {
      "Name": "IncludeCertChain",
      "DisplayName": "Include Certificate Chain",
      "Description": "Should the certificate chain be included when performing an enrollment?",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": false
    },
    {
      "Name": "MountPoint",
      "DisplayName": "Mount Point",
      "Description": "The base mount point of the secrets engine.  If using Vault Namespaces, include the namespace; ie. <namespace>/<mount point>",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false
    },
    {
      "Name": "PassphrasePath",
      "DisplayName": "Private Key Path",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "Description": "This is the path to the secret that contains the PEM-encoded private key. Optional - omit for CA trust chain / certificate-only PEM stores that have no private key. Unlike other Key-Value store types, no sibling-secret convention is assumed when this is omitted."
    }
  ],
  "EntryParameters": [],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default",
    "StorePassword": {
      "Description": "Vault token that will be used for authenticating",
      "IsPAMEligible": true
    }
  }
}
'@

Invoke-RestMethod -Uri "https://$KeyfactorHostname/$KeyfactorApiPath/CertificateStoreTypes" -Method POST -Headers $Headers -Body $Body

Write-Host "Creating store type: HCVKVJKS"
$Body = @'
{
  "Name": "Hashicorp Vault Key-Value JKS",
  "ShortName": "HCVKVJKS",
  "Capability": "HCVKVJKS",
  "LocalStore": false,
  "StorePathType": "",
  "StorePathValue": "example: '/mycerts/certstore.jks?b64cert'",
  "PrivateKeyAllowed": "Optional",
  "JobProperties": [
    {
      "Name": "DiscoverySuffix",
      "DisplayName": "Discovery Suffix",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "_jks",
      "Required": false,
      "Description": "The secret-key-name suffix Discovery jobs use to identify candidate JKS certificate secrets. Defaults to '_jks'."
    }
  ],
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required",
  "SupportedOperations": {
    "Add": true,
    "Create": true,
    "Discovery": true,
    "Enrollment": false,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "ServerUsername",
      "DisplayName": "Server Username",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true,
      "IsPAMEligible": true,
      "Description": "The base URI (and port) to the instance of Hashicorp Vault ex: https://localhost:8200"
    },
    {
      "Name": "ServerPassword",
      "DisplayName": "Server Password",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true,
      "IsPAMEligible": true,
      "Description": "Vault token that will be used by the Orchestrator integration for authenticating and performing operations in the Vault instance"
    },
    {
      "Name": "IncludeCertChain",
      "DisplayName": "Include Certificate Chain",
      "Description": "Should the certificate chain be included when performing an enrollment?",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": false
    },
    {
      "Name": "MountPoint",
      "DisplayName": "Mount Point",
      "Description": "The base mount point of the secrets engine.  If using Vault Namespaces, include the namespace; ie. <namespace>/<mount point>",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false
    },
    {
      "Name": "PassphrasePath",
      "DisplayName": "Passphrase Path",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "Description": "This is the path to the secret that contains the passphrase to the cert store file.  If empty or omitted, assume the secret is named 'passphrase' on the same level as the certificate store secret."
    }
  ],
  "EntryParameters": [],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default",
    "StorePassword": {
      "Description": "Vault token that will be used for authenticating",
      "IsPAMEligible": true
    }
  }
}
'@

Invoke-RestMethod -Uri "https://$KeyfactorHostname/$KeyfactorApiPath/CertificateStoreTypes" -Method POST -Headers $Headers -Body $Body

Write-Host "Creating store type: HCVKVP12"
$Body = @'
{
  "Name": "Hashicorp Vault Key-Value PKCS12",
  "ShortName": "HCVKVP12",
  "Capability": "HCVKVP12",
  "LocalStore": false,
  "StorePathType": "",
  "StorePathValue": "example: '/mycerts/certstore.p12?b64cert'",
  "PrivateKeyAllowed": "Optional",
  "JobProperties": [
    {
      "Name": "DiscoverySuffix",
      "DisplayName": "Discovery Suffix",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "_p12",
      "Required": false,
      "Description": "The secret-key-name suffix Discovery jobs use to identify candidate PKCS12 certificate secrets. Defaults to '_p12'."
    }
  ],
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required",
  "SupportedOperations": {
    "Add": true,
    "Create": true,
    "Discovery": true,
    "Enrollment": false,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "ServerUsername",
      "DisplayName": "Server Username",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true,
      "IsPAMEligible": true,
      "Description": "The base URI (and port) to the instance of Hashicorp Vault ex: https://localhost:8200"
    },
    {
      "Name": "ServerPassword",
      "DisplayName": "Server Password",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true,
      "IsPAMEligible": true,
      "Description": "Vault token that will be used by the Orchestrator integration for authenticating and performing operations in the Vault instance"
    },
    {
      "Name": "IncludeCertChain",
      "DisplayName": "Include Certificate Chain",
      "Description": "Should the certificate chain be included when performing an enrollment?",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": false
    },
    {
      "Name": "MountPoint",
      "DisplayName": "Mount Point",
      "Description": "The base mount point of the secrets engine.  If using Vault Namespaces, include the namespace; ie. <namespace>/<mount point>",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false
    },
    {
      "Name": "PassphrasePath",
      "DisplayName": "Passphrase Path",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "Description": "This is the path to the secret that contains the passphrase to the cert store file.  If empty or omitted, assume the secret is named 'passphrase' on the same level as the certificate store secret."
    }
  ],
  "EntryParameters": [],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default",
    "StorePassword": {
      "Description": "Vault token that will be used for authenticating",
      "IsPAMEligible": true
    }
  }
}
'@

Invoke-RestMethod -Uri "https://$KeyfactorHostname/$KeyfactorApiPath/CertificateStoreTypes" -Method POST -Headers $Headers -Body $Body

Write-Host "Creating store type: HCVKVPFX"
$Body = @'
{
  "Name": "Hashicorp Vault Key-Value PFX",
  "ShortName": "HCVKVPFX",
  "Capability": "HCVKVPFX",
  "LocalStore": false,
  "StorePathType": "",
  "StorePathValue": "example: '/mycerts/certstore.pfx?b64cert'",
  "PrivateKeyAllowed": "Optional",
  "JobProperties": [
    {
      "Name": "DiscoverySuffix",
      "DisplayName": "Discovery Suffix",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "_pfx",
      "Required": false,
      "Description": "The secret-key-name suffix Discovery jobs use to identify candidate PFX certificate secrets. Defaults to '_pfx'."
    }
  ],
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required",
  "SupportedOperations": {
    "Add": true,
    "Create": true,
    "Discovery": true,
    "Enrollment": false,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "ServerUsername",
      "DisplayName": "Server Username",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true,
      "IsPAMEligible": true,
      "Description": "The base URI (and port) to the instance of Hashicorp Vault ex: https://localhost:8200"
    },
    {
      "Name": "ServerPassword",
      "DisplayName": "Server Password",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true,
      "IsPAMEligible": true,
      "Description": "Vault token that will be used by the Orchestrator integration for authenticating and performing operations in the Vault instance"
    },
    {
      "Name": "IncludeCertChain",
      "DisplayName": "Include Certificate Chain",
      "Description": "Should the certificate chain be included when performing an enrollment?",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": false
    },
    {
      "Name": "MountPoint",
      "DisplayName": "Mount Point",
      "Description": "The base mount point of the secrets engine.  If using Vault Namespaces, include the namespace; ie. <namespace>/<mount point>",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false
    },
    {
      "Name": "PassphrasePath",
      "DisplayName": "Passphrase Path",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "Description": "This is the path to the secret that contains the passphrase to the cert store file.  If empty or omitted, assume the secret is named 'passphrase' on the same level as the certificate store secret."
    }
  ],
  "EntryParameters": [],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default",
    "StorePassword": {
      "Description": "Vault token that will be used for authenticating",
      "IsPAMEligible": true
    }
  }
}
'@

Invoke-RestMethod -Uri "https://$KeyfactorHostname/$KeyfactorApiPath/CertificateStoreTypes" -Method POST -Headers $Headers -Body $Body

