# Creates all 5 store types via the Keyfactor Command REST API
# using PowerShell Invoke-RestMethod.
#
# Authentication (first matching method is used):
#   OAuth access token:   KEYFACTOR_AUTH_ACCESS_TOKEN
#   OAuth client creds:   KEYFACTOR_AUTH_CLIENT_ID + KEYFACTOR_AUTH_CLIENT_SECRET
#                         + KEYFACTOR_AUTH_TOKEN_URL
#   Basic auth (AD):      KEYFACTOR_USERNAME + KEYFACTOR_PASSWORD + KEYFACTOR_DOMAIN
#
# Always required:
#   KEYFACTOR_HOSTNAME    Command hostname (e.g. my-command.example.com)
#
# Auto-generated by doctool generate-store-type-scripts — do not edit by hand.

if (-not $env:KEYFACTOR_HOSTNAME) {
    Write-Error "KEYFACTOR_HOSTNAME is required"
    exit 1
}

$uri     = "https://$($env:KEYFACTOR_HOSTNAME)/keyfactorapi/certificatestoretypes"
$headers = @{
    'Content-Type'               = "application/json"
    'x-keyfactor-requested-with' = "APIClient"
}

# ---------------------------------------------------------------------------
# Resolve auth
# ---------------------------------------------------------------------------
if ($env:KEYFACTOR_AUTH_ACCESS_TOKEN) {
    $headers['Authorization'] = "Bearer $($env:KEYFACTOR_AUTH_ACCESS_TOKEN)"
} elseif ($env:KEYFACTOR_AUTH_CLIENT_ID -and $env:KEYFACTOR_AUTH_CLIENT_SECRET -and $env:KEYFACTOR_AUTH_TOKEN_URL) {
    Write-Host "Fetching OAuth token..."
    $tokenBody = @{
        grant_type    = 'client_credentials'
        client_id     = $env:KEYFACTOR_AUTH_CLIENT_ID
        client_secret = $env:KEYFACTOR_AUTH_CLIENT_SECRET
    }
    $tokenResp = Invoke-RestMethod -Method Post -Uri $env:KEYFACTOR_AUTH_TOKEN_URL -Body $tokenBody
    $headers['Authorization'] = "Bearer $($tokenResp.access_token)"
} elseif ($env:KEYFACTOR_USERNAME -and $env:KEYFACTOR_PASSWORD -and $env:KEYFACTOR_DOMAIN) {
    $cred = [System.Convert]::ToBase64String(
        [System.Text.Encoding]::ASCII.GetBytes(
            "$($env:KEYFACTOR_USERNAME)@$($env:KEYFACTOR_DOMAIN):$($env:KEYFACTOR_PASSWORD)"))
    $headers['Authorization'] = "Basic $cred"
} else {
    Write-Error ("Authentication required. Set one of:`n" +
        "  KEYFACTOR_AUTH_ACCESS_TOKEN`n" +
        "  KEYFACTOR_AUTH_CLIENT_ID + KEYFACTOR_AUTH_CLIENT_SECRET + KEYFACTOR_AUTH_TOKEN_URL`n" +
        "  KEYFACTOR_USERNAME + KEYFACTOR_PASSWORD + KEYFACTOR_DOMAIN")
    exit 1
}

function New-StoreType {
    param([string]$Name, [string]$Body)
    Write-Host "Creating $Name store type..."
    try {
        Invoke-RestMethod -Method Post -Uri $uri -Headers $headers -Body $Body -ContentType "application/json" | Out-Null
        Write-Host "  OK"
    } catch {
        Write-Warning "  FAILED: $($_.Exception.Message)"
    }
}

# ---------------------------------------------------------------------------
# HCVPKI — This can be any value to help uniquely identify the store.  It is not used by this integration.
# ---------------------------------------------------------------------------
New-StoreType "HCVPKI" @'
{
  "Name": "Hashicorp Vault PKI",
  "ShortName": "HCVPKI",
  "Capability": "HCVPKI",
  "LocalStore": false,
  "StorePathDescription": "For HCVPKI, this will be '/'",
  "JobProperties": [],
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "PrivateKeyAllowed": "Forbidden",
  "CustomAliasAllowed": "Forbidden",
  "StorePathType": "Fixed",
  "StorePathValue": "/",
  "SupportedOperations": {
    "Add": false,
    "Create": false,
    "Discovery": false,
    "Enrollment": false,
    "Remove": false
  },
  "Properties": [
    {
      "Name": "MountPoint",
      "DisplayName": "Mount Point",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true
    },
    {
      "Name": "PassphrasePath",
      "DisplayName": "Passphrase Path",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false
    }
  ],
  "EntryParameters": [],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default",
    "StorePassword": {
      "Description": "Vault token that will be used for authenticating",
      "IsPAMEligible": true
    }
  }
}
'@

# ---------------------------------------------------------------------------
# HCVKVPEM — This can be any value to help uniquely identify the store.  It is not used by this integration.
# ---------------------------------------------------------------------------
New-StoreType "HCVKVPEM" @'
{
  "Name": "Hashicorp Vault Key-Value PEM",
  "ShortName": "HCVKVPEM",
  "Capability": "HCVKVPEM",
  "LocalStore": false,
  "StorePathDescription": "This is the path after mount point where the certificates will be stored.",
  "PrivateKeyAllowed": "Optional",
  "JobProperties": [],
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required",
  "SupportedOperations": {
    "Add": true,
    "Create": true,
    "Discovery": true,
    "Enrollment": false,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "SubfolderInventory",
      "DisplayName": "Subfolder Inventory",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": false
    },
    {
      "Name": "IncludeCertChain",
      "DisplayName": "Include Certificate Chain",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": false
    },
    {
      "Name": "MountPoint",
      "DisplayName": "Mount Point",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false
    }
  ],
  "EntryParameters": [],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default",
    "StorePassword": {
      "Description": "Vault token that will be used for authenticating",
      "IsPAMEligible": true
    }
  }
}
'@

# ---------------------------------------------------------------------------
# HCVKVJKS — This can be any value to help uniquely identify the store.  It is not used by this integration.
# ---------------------------------------------------------------------------
New-StoreType "HCVKVJKS" @'
{
  "Name": "Hashicorp Vault Key-Value JKS",
  "ShortName": "HCVKVJKS",
  "Capability": "HCVKVJKS",
  "StorePathDescription": "This is the path to the secret containing the store.",
  "LocalStore": false,
  "StorePathType": "",
  "StorePathValue": "example: '/mycerts/certstore.jks?b64cert'",
  "PrivateKeyAllowed": "Optional",
  "JobProperties": [],
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required",
  "SupportedOperations": {
    "Add": true,
    "Create": true,
    "Discovery": true,
    "Enrollment": false,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "IncludeCertChain",
      "DisplayName": "Include Certificate Chain",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": false
    },
    {
      "Name": "MountPoint",
      "DisplayName": "Mount Point",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false
    },
    {
      "Name": "PassphrasePath",
      "DisplayName": "Passphrase Path",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false
    }
  ],
  "EntryParameters": [],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default",
    "StorePassword": {
      "Description": "Vault token that will be used for authenticating",
      "IsPAMEligible": true
    }
  }
}
'@

# ---------------------------------------------------------------------------
# HCVKVP12 — This can be any value to help uniquely identify the store.  It is not used by this integration.
# ---------------------------------------------------------------------------
New-StoreType "HCVKVP12" @'
{
  "Name": "Hashicorp Vault Key-Value PKCS12",
  "ShortName": "HCVKVP12",
  "Capability": "HCVKVP12",
  "StorePathDescription": "This is the path to the secret containing the store.",
  "LocalStore": false,
  "StorePathType": "",
  "StorePathValue": "example: '/mycerts/certstore.p12?b64cert'",
  "PrivateKeyAllowed": "Optional",
  "JobProperties": [],
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required",
  "SupportedOperations": {
    "Add": true,
    "Create": true,
    "Discovery": true,
    "Enrollment": false,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "IncludeCertChain",
      "DisplayName": "Include Certificate Chain",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": false
    },
    {
      "Name": "MountPoint",
      "DisplayName": "Mount Point",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false
    },
    {
      "Name": "PassphrasePath",
      "DisplayName": "Passphrase Path",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false
    }
  ],
  "EntryParameters": [],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default",
    "StorePassword": {
      "Description": "Vault token that will be used for authenticating",
      "IsPAMEligible": true
    }
  }
}
'@

# ---------------------------------------------------------------------------
# HCVKVPFX — This can be any value to help uniquely identify the store.  It is not used by this integration.
# ---------------------------------------------------------------------------
New-StoreType "HCVKVPFX" @'
{
  "Name": "Hashicorp Vault Key-Value PFX",
  "ShortName": "HCVKVPFX",
  "Capability": "HCVKVPFX",
  "StorePathDescription": "This is the path to the secret containing the store.",
  "LocalStore": false,
  "StorePathType": "",
  "StorePathValue": "example: '/mycerts/certstore.pfx?b64cert'",
  "PrivateKeyAllowed": "Optional",
  "JobProperties": [],
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required",
  "SupportedOperations": {
    "Add": true,
    "Create": true,
    "Discovery": true,
    "Enrollment": false,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "IncludeCertChain",
      "DisplayName": "Include Certificate Chain",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": false
    },
    {
      "Name": "MountPoint",
      "DisplayName": "Mount Point",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false
    },
    {
      "Name": "PassphrasePath",
      "DisplayName": "Passphrase Path",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false
    }
  ],
  "EntryParameters": [],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default",
    "StorePassword": {
      "Description": "Vault token that will be used for authenticating",
      "IsPAMEligible": true
    }
  }
}
'@


Write-Host "Completed."
