#!/usr/bin/env bash

# Creates all 5 store types via the Keyfactor Command REST API using curl.
#
# Authentication (first matching method is used):
#   OAuth access token:   KEYFACTOR_AUTH_ACCESS_TOKEN
#   OAuth client creds:   KEYFACTOR_AUTH_CLIENT_ID + KEYFACTOR_AUTH_CLIENT_SECRET
#                         + KEYFACTOR_AUTH_TOKEN_URL
#   Basic auth (AD):      KEYFACTOR_USERNAME + KEYFACTOR_PASSWORD + KEYFACTOR_DOMAIN
#
# Always required:
#   KEYFACTOR_HOSTNAME    Command hostname (e.g. my-command.example.com)
#
# Auto-generated by doctool generate-store-type-scripts — do not edit by hand.

if [ -z "${KEYFACTOR_HOSTNAME}" ]; then
    echo "ERROR: KEYFACTOR_HOSTNAME is required"
    exit 1
fi

BASE_URL="https://${KEYFACTOR_HOSTNAME}/keyfactorapi"

# ---------------------------------------------------------------------------
# Resolve auth
# ---------------------------------------------------------------------------
if [ -n "${KEYFACTOR_AUTH_ACCESS_TOKEN}" ]; then
    BEARER_TOKEN="${KEYFACTOR_AUTH_ACCESS_TOKEN}"
elif [ -n "${KEYFACTOR_AUTH_CLIENT_ID}" ] && [ -n "${KEYFACTOR_AUTH_CLIENT_SECRET}" ] && [ -n "${KEYFACTOR_AUTH_TOKEN_URL}" ]; then
    echo "Fetching OAuth token..."
    BEARER_TOKEN=$(curl -s -X POST "${KEYFACTOR_AUTH_TOKEN_URL}" \
        -H "Content-Type: application/x-www-form-urlencoded" \
        --data-urlencode "grant_type=client_credentials" \
        --data-urlencode "client_id=${KEYFACTOR_AUTH_CLIENT_ID}" \
        --data-urlencode "client_secret=${KEYFACTOR_AUTH_CLIENT_SECRET}" | jq -r '.access_token')
    if [ -z "${BEARER_TOKEN}" ] || [ "${BEARER_TOKEN}" = "null" ]; then
        echo "ERROR: Failed to fetch OAuth token from ${KEYFACTOR_AUTH_TOKEN_URL}"
        exit 1
    fi
elif [ -n "${KEYFACTOR_USERNAME}" ] && [ -n "${KEYFACTOR_PASSWORD}" ] && [ -n "${KEYFACTOR_DOMAIN}" ]; then
    BEARER_TOKEN=""
else
    echo "ERROR: Authentication required. Set one of:"
    echo "  KEYFACTOR_AUTH_ACCESS_TOKEN"
    echo "  KEYFACTOR_AUTH_CLIENT_ID + KEYFACTOR_AUTH_CLIENT_SECRET + KEYFACTOR_AUTH_TOKEN_URL"
    echo "  KEYFACTOR_USERNAME + KEYFACTOR_PASSWORD + KEYFACTOR_DOMAIN"
    exit 1
fi

if [ -n "${BEARER_TOKEN}" ]; then
    CURL_AUTH=("-H" "Authorization: Bearer ${BEARER_TOKEN}")
else
    CURL_AUTH=("-u" "${KEYFACTOR_USERNAME}@${KEYFACTOR_DOMAIN}:${KEYFACTOR_PASSWORD}")
fi

create_store_type() {
    local name="$1"
    local body="$2"
    echo "Creating ${name} store type..."
    response=$(curl -s -o /dev/null -w "%{http_code}" \
        -X POST "${BASE_URL}/certificatestoretypes" \
        -H "Content-Type: application/json" \
        -H "x-keyfactor-requested-with: APIClient" \
        "${CURL_AUTH[@]}" \
        -d "${body}")
    if [ "$response" = "200" ] || [ "$response" = "201" ]; then
        echo "  OK (HTTP ${response})"
    else
        echo "  FAILED (HTTP ${response})"
    fi
}

# ---------------------------------------------------------------------------
# HCVPKI — This can be any value to help uniquely identify the store.  It is not used by this integration.
# ---------------------------------------------------------------------------
create_store_type "HCVPKI" '{
  "Name": "Hashicorp Vault PKI",
  "ShortName": "HCVPKI",
  "Capability": "HCVPKI",
  "LocalStore": false,
  "StorePathDescription": "For HCVPKI, this will be '/'",
  "JobProperties": [],
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "PrivateKeyAllowed": "Forbidden",
  "CustomAliasAllowed": "Forbidden",
  "StorePathType": "Fixed",
  "StorePathValue": "/",
  "SupportedOperations": {
    "Add": false,
    "Create": false,
    "Discovery": false,
    "Enrollment": false,
    "Remove": false
  },
  "Properties": [
    {
      "Name": "MountPoint",
      "DisplayName": "Mount Point",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true
    },
    {
      "Name": "PassphrasePath",
      "DisplayName": "Passphrase Path",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false
    }
  ],
  "EntryParameters": [],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default",
    "StorePassword": {
      "Description": "Vault token that will be used for authenticating",
      "IsPAMEligible": true
    }
  }
}'

# ---------------------------------------------------------------------------
# HCVKVPEM — This can be any value to help uniquely identify the store.  It is not used by this integration.
# ---------------------------------------------------------------------------
create_store_type "HCVKVPEM" '{
  "Name": "Hashicorp Vault Key-Value PEM",
  "ShortName": "HCVKVPEM",
  "Capability": "HCVKVPEM",
  "LocalStore": false,
  "StorePathDescription": "This is the path after mount point where the certificates will be stored.",
  "PrivateKeyAllowed": "Optional",
  "JobProperties": [],
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required",
  "SupportedOperations": {
    "Add": true,
    "Create": true,
    "Discovery": true,
    "Enrollment": false,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "SubfolderInventory",
      "DisplayName": "Subfolder Inventory",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": false
    },
    {
      "Name": "IncludeCertChain",
      "DisplayName": "Include Certificate Chain",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": false
    },
    {
      "Name": "MountPoint",
      "DisplayName": "Mount Point",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false
    }
  ],
  "EntryParameters": [],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default",
    "StorePassword": {
      "Description": "Vault token that will be used for authenticating",
      "IsPAMEligible": true
    }
  }
}'

# ---------------------------------------------------------------------------
# HCVKVJKS — This can be any value to help uniquely identify the store.  It is not used by this integration.
# ---------------------------------------------------------------------------
create_store_type "HCVKVJKS" '{
  "Name": "Hashicorp Vault Key-Value JKS",
  "ShortName": "HCVKVJKS",
  "Capability": "HCVKVJKS",
  "StorePathDescription": "This is the path to the secret containing the store.",
  "LocalStore": false,
  "StorePathType": "",
  "StorePathValue": "example: '/mycerts/certstore.jks?b64cert'",
  "PrivateKeyAllowed": "Optional",
  "JobProperties": [],
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required",
  "SupportedOperations": {
    "Add": true,
    "Create": true,
    "Discovery": true,
    "Enrollment": false,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "IncludeCertChain",
      "DisplayName": "Include Certificate Chain",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": false
    },
    {
      "Name": "MountPoint",
      "DisplayName": "Mount Point",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false
    },
    {
      "Name": "PassphrasePath",
      "DisplayName": "Passphrase Path",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false
    }
  ],
  "EntryParameters": [],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default",
    "StorePassword": {
      "Description": "Vault token that will be used for authenticating",
      "IsPAMEligible": true
    }
  }
}'

# ---------------------------------------------------------------------------
# HCVKVP12 — This can be any value to help uniquely identify the store.  It is not used by this integration.
# ---------------------------------------------------------------------------
create_store_type "HCVKVP12" '{
  "Name": "Hashicorp Vault Key-Value PKCS12",
  "ShortName": "HCVKVP12",
  "Capability": "HCVKVP12",
  "StorePathDescription": "This is the path to the secret containing the store.",
  "LocalStore": false,
  "StorePathType": "",
  "StorePathValue": "example: '/mycerts/certstore.p12?b64cert'",
  "PrivateKeyAllowed": "Optional",
  "JobProperties": [],
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required",
  "SupportedOperations": {
    "Add": true,
    "Create": true,
    "Discovery": true,
    "Enrollment": false,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "IncludeCertChain",
      "DisplayName": "Include Certificate Chain",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": false
    },
    {
      "Name": "MountPoint",
      "DisplayName": "Mount Point",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false
    },
    {
      "Name": "PassphrasePath",
      "DisplayName": "Passphrase Path",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false
    }
  ],
  "EntryParameters": [],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default",
    "StorePassword": {
      "Description": "Vault token that will be used for authenticating",
      "IsPAMEligible": true
    }
  }
}'

# ---------------------------------------------------------------------------
# HCVKVPFX — This can be any value to help uniquely identify the store.  It is not used by this integration.
# ---------------------------------------------------------------------------
create_store_type "HCVKVPFX" '{
  "Name": "Hashicorp Vault Key-Value PFX",
  "ShortName": "HCVKVPFX",
  "Capability": "HCVKVPFX",
  "StorePathDescription": "This is the path to the secret containing the store.",
  "LocalStore": false,
  "StorePathType": "",
  "StorePathValue": "example: '/mycerts/certstore.pfx?b64cert'",
  "PrivateKeyAllowed": "Optional",
  "JobProperties": [],
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required",
  "SupportedOperations": {
    "Add": true,
    "Create": true,
    "Discovery": true,
    "Enrollment": false,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "IncludeCertChain",
      "DisplayName": "Include Certificate Chain",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": false
    },
    {
      "Name": "MountPoint",
      "DisplayName": "Mount Point",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false
    },
    {
      "Name": "PassphrasePath",
      "DisplayName": "Passphrase Path",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false
    }
  ],
  "EntryParameters": [],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default",
    "StorePassword": {
      "Description": "Vault token that will be used for authenticating",
      "IsPAMEligible": true
    }
  }
}'


echo "Completed."
