#!/bin/bash
# Store Type creation script using curl
# Generated by Doctool

set -e

# Configuration - set these variables before running
KEYFACTOR_HOSTNAME="${KEYFACTOR_HOSTNAME}"
KEYFACTOR_API_PATH="${KEYFACTOR_API_PATH:-KeyfactorAPI}"
KEYFACTOR_AUTH_TOKEN="${KEYFACTOR_AUTH_TOKEN}"

echo "Creating store type: HCVPKI"
curl -s -X POST "https://${KEYFACTOR_HOSTNAME}/${KEYFACTOR_API_PATH}/CertificateStoreTypes" \
  -H "Authorization: Bearer ${KEYFACTOR_AUTH_TOKEN}" \
  -H "Content-Type: application/json" \
  -H "x-keyfactor-requested-with: APIClient" \
  -d '{
  "Name": "Hashicorp Vault PKI",
  "ShortName": "HCVPKI",
  "Capability": "HCVPKI",
  "LocalStore": false,
  "JobProperties": [],
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "PrivateKeyAllowed": "Forbidden",
  "CustomAliasAllowed": "Forbidden",
  "StorePathType": "Fixed",
  "StorePathValue": "/",
  "SupportedOperations": {
    "Add": false,
    "Create": false,
    "Discovery": false,
    "Enrollment": false,
    "Remove": false
  },
  "Properties": [
    {
      "Name": "ServerUsername",
      "DisplayName": "Server Username",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true,
      "IsPAMEligible": true,
      "Description": "The base URI (and port) to the instance of Hashicorp Vault ex: https://localhost:8200"
    },
    {
      "Name": "ServerPassword",
      "DisplayName": "Server Password",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true,
      "Description": "Vault token that will be used by the Orchestrator integration for authenticating and performing operations in the Vault instance. Required unless 'Use OAuth 2.0 (Client Credentials)' is enabled."
    },
    {
      "Name": "UseOAuth",
      "DisplayName": "Use OAuth 2.0 (Client Credentials)",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": false,
      "Description": "Enables OAuth 2.0 Client Credentials authentication: the orchestrator obtains a JWT from the configured IdP (e.g. PingFederate, Microsoft Entra ID) and exchanges it for a short-lived Vault token via Vault's JWT auth method, instead of using a static 'Server Password' Vault token."
    },
    {
      "Name": "ClientId",
      "DisplayName": "Client ID",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true,
      "Description": "The OAuth 2.0 Client ID registered with your IdP. Only used when 'Use OAuth 2.0 (Client Credentials)' is enabled."
    },
    {
      "Name": "ClientSecret",
      "DisplayName": "Client Secret",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true,
      "Description": "The OAuth 2.0 Client Secret for the above Client ID. Only used when 'Use OAuth 2.0 (Client Credentials)' is enabled."
    },
    {
      "Name": "OAuthUrl",
      "DisplayName": "OAuth Token Endpoint",
      "Type": "String",
      "DependsOn": "UseOAuth",
      "DefaultValue": "",
      "Required": false,
      "Description": "The IdP's OAuth 2.0 token endpoint URL used to obtain a JWT via the Client Credentials grant. Only used when 'Use OAuth 2.0 (Client Credentials)' is enabled."
    },
    {
      "Name": "Scope",
      "DisplayName": "OAuth Scope",
      "Type": "String",
      "DependsOn": "UseOAuth",
      "DefaultValue": "",
      "Required": false,
      "Description": "Optional OAuth 2.0 scope to request from the IdP (e.g. Entra ID typically needs 'api://<app-id-uri>/.default'). Only used when 'Use OAuth 2.0 (Client Credentials)' is enabled."
    },
    {
      "Name": "VaultRoleName",
      "DisplayName": "Vault Role Name",
      "Type": "String",
      "DependsOn": "UseOAuth",
      "DefaultValue": "",
      "Required": false,
      "Description": "The name of the Vault role, configured under the JWT auth mount (e.g. 'auth/jwt/role/<name>'), to authenticate against using the JWT obtained from the IdP. Only used when 'Use OAuth 2.0 (Client Credentials)' is enabled."
    },
    {
      "Name": "AuthMountPoint",
      "DisplayName": "JWT Auth Mount Point",
      "Type": "String",
      "DependsOn": "UseOAuth",
      "DefaultValue": "jwt/",
      "Required": false,
      "Description": "The mount point of Vault's JWT auth method used to exchange the IdP-issued JWT for a Vault token. Only used when 'Use OAuth 2.0 (Client Credentials)' is enabled."
    },
    {
      "Name": "MountPoint",
      "DisplayName": "Mount Point",
      "Description": "This is the mount point of the instance of the PKI or Keyfactor secrets engine plugin.  If using enterprise namespaces: <namespace>/<mount point>",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true
    },
    {
      "Name": "PassphrasePath",
      "DisplayName": "Passphrase Path",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "Description": "This is the path to the secret that contains the passphrase to the cert store file.  If empty or omitted, assume the secret is named 'passphrase' on the same level as the certificate store secret."
    }
  ],
  "EntryParameters": [],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default",
    "StorePassword": {
      "Description": "Vault token that will be used for authenticating",
      "IsPAMEligible": true
    }
  }
}'

echo "Creating store type: HCVKVPEM"
curl -s -X POST "https://${KEYFACTOR_HOSTNAME}/${KEYFACTOR_API_PATH}/CertificateStoreTypes" \
  -H "Authorization: Bearer ${KEYFACTOR_AUTH_TOKEN}" \
  -H "Content-Type: application/json" \
  -H "x-keyfactor-requested-with: APIClient" \
  -d '{
  "Name": "Hashicorp Vault Key-Value PEM",
  "ShortName": "HCVKVPEM",
  "Capability": "HCVKVPEM",
  "LocalStore": false,
  "StorePathType": "",
  "StorePathValue": "example: '/mycerts/mycert_pem?b64cert'",
  "PrivateKeyAllowed": "Optional",
  "JobProperties": [
    {
      "Name": "DiscoverySuffix",
      "DisplayName": "Discovery Suffix",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "_pem",
      "Required": false,
      "Description": "The secret-key-name suffix Discovery jobs use to identify candidate PEM certificate secrets. Defaults to '_pem'."
    }
  ],
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required",
  "SupportedOperations": {
    "Add": true,
    "Create": true,
    "Discovery": true,
    "Enrollment": false,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "ServerUsername",
      "DisplayName": "Server Username",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true,
      "IsPAMEligible": true,
      "Description": "The base URI (and port) to the instance of Hashicorp Vault ex: https://localhost:8200"
    },
    {
      "Name": "ServerPassword",
      "DisplayName": "Server Password",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true,
      "Description": "Vault token that will be used by the Orchestrator integration for authenticating and performing operations in the Vault instance. Required unless 'Use OAuth 2.0 (Client Credentials)' is enabled."
    },
    {
      "Name": "UseOAuth",
      "DisplayName": "Use OAuth 2.0 (Client Credentials)",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": false,
      "Description": "Enables OAuth 2.0 Client Credentials authentication: the orchestrator obtains a JWT from the configured IdP (e.g. PingFederate, Microsoft Entra ID) and exchanges it for a short-lived Vault token via Vault's JWT auth method, instead of using a static 'Server Password' Vault token."
    },
    {
      "Name": "ClientId",
      "DisplayName": "Client ID",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true,
      "Description": "The OAuth 2.0 Client ID registered with your IdP. Only used when 'Use OAuth 2.0 (Client Credentials)' is enabled."
    },
    {
      "Name": "ClientSecret",
      "DisplayName": "Client Secret",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true,
      "Description": "The OAuth 2.0 Client Secret for the above Client ID. Only used when 'Use OAuth 2.0 (Client Credentials)' is enabled."
    },
    {
      "Name": "OAuthUrl",
      "DisplayName": "OAuth Token Endpoint",
      "Type": "String",
      "DependsOn": "UseOAuth",
      "DefaultValue": "",
      "Required": false,
      "Description": "The IdP's OAuth 2.0 token endpoint URL used to obtain a JWT via the Client Credentials grant. Only used when 'Use OAuth 2.0 (Client Credentials)' is enabled."
    },
    {
      "Name": "Scope",
      "DisplayName": "OAuth Scope",
      "Type": "String",
      "DependsOn": "UseOAuth",
      "DefaultValue": "",
      "Required": false,
      "Description": "Optional OAuth 2.0 scope to request from the IdP (e.g. Entra ID typically needs 'api://<app-id-uri>/.default'). Only used when 'Use OAuth 2.0 (Client Credentials)' is enabled."
    },
    {
      "Name": "VaultRoleName",
      "DisplayName": "Vault Role Name",
      "Type": "String",
      "DependsOn": "UseOAuth",
      "DefaultValue": "",
      "Required": false,
      "Description": "The name of the Vault role, configured under the JWT auth mount (e.g. 'auth/jwt/role/<name>'), to authenticate against using the JWT obtained from the IdP. Only used when 'Use OAuth 2.0 (Client Credentials)' is enabled."
    },
    {
      "Name": "AuthMountPoint",
      "DisplayName": "JWT Auth Mount Point",
      "Type": "String",
      "DependsOn": "UseOAuth",
      "DefaultValue": "jwt/",
      "Required": false,
      "Description": "The mount point of Vault's JWT auth method used to exchange the IdP-issued JWT for a Vault token. Only used when 'Use OAuth 2.0 (Client Credentials)' is enabled."
    },
    {
      "Name": "IncludeCertChain",
      "DisplayName": "Include Certificate Chain",
      "Description": "Should the certificate chain be included when performing an enrollment?",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": false
    },
    {
      "Name": "MountPoint",
      "DisplayName": "Mount Point",
      "Description": "The base mount point of the secrets engine.  If using Vault Namespaces, include the namespace; ie. <namespace>/<mount point>",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false
    },
    {
      "Name": "PrivateKeyPath",
      "DisplayName": "Private Key Path",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "Description": "This is the path to the secret that contains the PEM-encoded private key. Optional — omit for CA trust chain / certificate-only PEM stores that have no private key. Unlike other Key-Value store types, no sibling-secret convention is assumed when this is omitted."
    }
  ],
  "EntryParameters": [],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default",
    "StorePassword": {
      "Description": "Vault token that will be used for authenticating",
      "IsPAMEligible": true
    }
  }
}'

echo "Creating store type: HCVKVJKS"
curl -s -X POST "https://${KEYFACTOR_HOSTNAME}/${KEYFACTOR_API_PATH}/CertificateStoreTypes" \
  -H "Authorization: Bearer ${KEYFACTOR_AUTH_TOKEN}" \
  -H "Content-Type: application/json" \
  -H "x-keyfactor-requested-with: APIClient" \
  -d '{
  "Name": "Hashicorp Vault Key-Value JKS",
  "ShortName": "HCVKVJKS",
  "Capability": "HCVKVJKS",
  "LocalStore": false,
  "StorePathType": "",
  "StorePathValue": "example: '/mycerts/certstore.jks?b64cert'",
  "PrivateKeyAllowed": "Optional",
  "JobProperties": [
    {
      "Name": "DiscoverySuffix",
      "DisplayName": "Discovery Suffix",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "_jks",
      "Required": false,
      "Description": "The secret-key-name suffix Discovery jobs use to identify candidate JKS certificate secrets. Defaults to '_jks'."
    }
  ],
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required",
  "SupportedOperations": {
    "Add": true,
    "Create": true,
    "Discovery": true,
    "Enrollment": false,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "ServerUsername",
      "DisplayName": "Server Username",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true,
      "IsPAMEligible": true,
      "Description": "The base URI (and port) to the instance of Hashicorp Vault ex: https://localhost:8200"
    },
    {
      "Name": "ServerPassword",
      "DisplayName": "Server Password",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true,
      "Description": "Vault token that will be used by the Orchestrator integration for authenticating and performing operations in the Vault instance. Required unless 'Use OAuth 2.0 (Client Credentials)' is enabled."
    },
    {
      "Name": "UseOAuth",
      "DisplayName": "Use OAuth 2.0 (Client Credentials)",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": false,
      "Description": "Enables OAuth 2.0 Client Credentials authentication: the orchestrator obtains a JWT from the configured IdP (e.g. PingFederate, Microsoft Entra ID) and exchanges it for a short-lived Vault token via Vault's JWT auth method, instead of using a static 'Server Password' Vault token."
    },
    {
      "Name": "ClientId",
      "DisplayName": "Client ID",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true,
      "Description": "The OAuth 2.0 Client ID registered with your IdP. Only used when 'Use OAuth 2.0 (Client Credentials)' is enabled."
    },
    {
      "Name": "ClientSecret",
      "DisplayName": "Client Secret",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true,
      "Description": "The OAuth 2.0 Client Secret for the above Client ID. Only used when 'Use OAuth 2.0 (Client Credentials)' is enabled."
    },
    {
      "Name": "OAuthUrl",
      "DisplayName": "OAuth Token Endpoint",
      "Type": "String",
      "DependsOn": "UseOAuth",
      "DefaultValue": "",
      "Required": false,
      "Description": "The IdP's OAuth 2.0 token endpoint URL used to obtain a JWT via the Client Credentials grant. Only used when 'Use OAuth 2.0 (Client Credentials)' is enabled."
    },
    {
      "Name": "Scope",
      "DisplayName": "OAuth Scope",
      "Type": "String",
      "DependsOn": "UseOAuth",
      "DefaultValue": "",
      "Required": false,
      "Description": "Optional OAuth 2.0 scope to request from the IdP (e.g. Entra ID typically needs 'api://<app-id-uri>/.default'). Only used when 'Use OAuth 2.0 (Client Credentials)' is enabled."
    },
    {
      "Name": "VaultRoleName",
      "DisplayName": "Vault Role Name",
      "Type": "String",
      "DependsOn": "UseOAuth",
      "DefaultValue": "",
      "Required": false,
      "Description": "The name of the Vault role, configured under the JWT auth mount (e.g. 'auth/jwt/role/<name>'), to authenticate against using the JWT obtained from the IdP. Only used when 'Use OAuth 2.0 (Client Credentials)' is enabled."
    },
    {
      "Name": "AuthMountPoint",
      "DisplayName": "JWT Auth Mount Point",
      "Type": "String",
      "DependsOn": "UseOAuth",
      "DefaultValue": "jwt/",
      "Required": false,
      "Description": "The mount point of Vault's JWT auth method used to exchange the IdP-issued JWT for a Vault token. Only used when 'Use OAuth 2.0 (Client Credentials)' is enabled."
    },
    {
      "Name": "IncludeCertChain",
      "DisplayName": "Include Certificate Chain",
      "Description": "Should the certificate chain be included when performing an enrollment?",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": false
    },
    {
      "Name": "MountPoint",
      "DisplayName": "Mount Point",
      "Description": "The base mount point of the secrets engine.  If using Vault Namespaces, include the namespace; ie. <namespace>/<mount point>",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false
    },
    {
      "Name": "PassphrasePath",
      "DisplayName": "Passphrase Path",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "Description": "This is the path to the secret that contains the passphrase to the cert store file.  If empty or omitted, assume the secret is named 'passphrase' on the same level as the certificate store secret."
    }
  ],
  "EntryParameters": [],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default",
    "StorePassword": {
      "Description": "Vault token that will be used for authenticating",
      "IsPAMEligible": true
    }
  }
}'

echo "Creating store type: HCVKVP12"
curl -s -X POST "https://${KEYFACTOR_HOSTNAME}/${KEYFACTOR_API_PATH}/CertificateStoreTypes" \
  -H "Authorization: Bearer ${KEYFACTOR_AUTH_TOKEN}" \
  -H "Content-Type: application/json" \
  -H "x-keyfactor-requested-with: APIClient" \
  -d '{
  "Name": "Hashicorp Vault Key-Value PKCS12",
  "ShortName": "HCVKVP12",
  "Capability": "HCVKVP12",
  "LocalStore": false,
  "StorePathType": "",
  "StorePathValue": "example: '/mycerts/certstore.p12?b64cert'",
  "PrivateKeyAllowed": "Optional",
  "JobProperties": [
    {
      "Name": "DiscoverySuffix",
      "DisplayName": "Discovery Suffix",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "_p12",
      "Required": false,
      "Description": "The secret-key-name suffix Discovery jobs use to identify candidate PKCS12 certificate secrets. Defaults to '_p12'."
    }
  ],
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required",
  "SupportedOperations": {
    "Add": true,
    "Create": true,
    "Discovery": true,
    "Enrollment": false,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "ServerUsername",
      "DisplayName": "Server Username",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true,
      "IsPAMEligible": true,
      "Description": "The base URI (and port) to the instance of Hashicorp Vault ex: https://localhost:8200"
    },
    {
      "Name": "ServerPassword",
      "DisplayName": "Server Password",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true,
      "Description": "Vault token that will be used by the Orchestrator integration for authenticating and performing operations in the Vault instance. Required unless 'Use OAuth 2.0 (Client Credentials)' is enabled."
    },
    {
      "Name": "UseOAuth",
      "DisplayName": "Use OAuth 2.0 (Client Credentials)",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": false,
      "Description": "Enables OAuth 2.0 Client Credentials authentication: the orchestrator obtains a JWT from the configured IdP (e.g. PingFederate, Microsoft Entra ID) and exchanges it for a short-lived Vault token via Vault's JWT auth method, instead of using a static 'Server Password' Vault token."
    },
    {
      "Name": "ClientId",
      "DisplayName": "Client ID",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true,
      "Description": "The OAuth 2.0 Client ID registered with your IdP. Only used when 'Use OAuth 2.0 (Client Credentials)' is enabled."
    },
    {
      "Name": "ClientSecret",
      "DisplayName": "Client Secret",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true,
      "Description": "The OAuth 2.0 Client Secret for the above Client ID. Only used when 'Use OAuth 2.0 (Client Credentials)' is enabled."
    },
    {
      "Name": "OAuthUrl",
      "DisplayName": "OAuth Token Endpoint",
      "Type": "String",
      "DependsOn": "UseOAuth",
      "DefaultValue": "",
      "Required": false,
      "Description": "The IdP's OAuth 2.0 token endpoint URL used to obtain a JWT via the Client Credentials grant. Only used when 'Use OAuth 2.0 (Client Credentials)' is enabled."
    },
    {
      "Name": "Scope",
      "DisplayName": "OAuth Scope",
      "Type": "String",
      "DependsOn": "UseOAuth",
      "DefaultValue": "",
      "Required": false,
      "Description": "Optional OAuth 2.0 scope to request from the IdP (e.g. Entra ID typically needs 'api://<app-id-uri>/.default'). Only used when 'Use OAuth 2.0 (Client Credentials)' is enabled."
    },
    {
      "Name": "VaultRoleName",
      "DisplayName": "Vault Role Name",
      "Type": "String",
      "DependsOn": "UseOAuth",
      "DefaultValue": "",
      "Required": false,
      "Description": "The name of the Vault role, configured under the JWT auth mount (e.g. 'auth/jwt/role/<name>'), to authenticate against using the JWT obtained from the IdP. Only used when 'Use OAuth 2.0 (Client Credentials)' is enabled."
    },
    {
      "Name": "AuthMountPoint",
      "DisplayName": "JWT Auth Mount Point",
      "Type": "String",
      "DependsOn": "UseOAuth",
      "DefaultValue": "jwt/",
      "Required": false,
      "Description": "The mount point of Vault's JWT auth method used to exchange the IdP-issued JWT for a Vault token. Only used when 'Use OAuth 2.0 (Client Credentials)' is enabled."
    },
    {
      "Name": "IncludeCertChain",
      "DisplayName": "Include Certificate Chain",
      "Description": "Should the certificate chain be included when performing an enrollment?",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": false
    },
    {
      "Name": "MountPoint",
      "DisplayName": "Mount Point",
      "Description": "The base mount point of the secrets engine.  If using Vault Namespaces, include the namespace; ie. <namespace>/<mount point>",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false
    },
    {
      "Name": "PassphrasePath",
      "DisplayName": "Passphrase Path",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "Description": "This is the path to the secret that contains the passphrase to the cert store file.  If empty or omitted, assume the secret is named 'passphrase' on the same level as the certificate store secret."
    }
  ],
  "EntryParameters": [],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default",
    "StorePassword": {
      "Description": "Vault token that will be used for authenticating",
      "IsPAMEligible": true
    }
  }
}'

echo "Creating store type: HCVKVPFX"
curl -s -X POST "https://${KEYFACTOR_HOSTNAME}/${KEYFACTOR_API_PATH}/CertificateStoreTypes" \
  -H "Authorization: Bearer ${KEYFACTOR_AUTH_TOKEN}" \
  -H "Content-Type: application/json" \
  -H "x-keyfactor-requested-with: APIClient" \
  -d '{
  "Name": "Hashicorp Vault Key-Value PFX",
  "ShortName": "HCVKVPFX",
  "Capability": "HCVKVPFX",
  "LocalStore": false,
  "StorePathType": "",
  "StorePathValue": "example: '/mycerts/certstore.pfx?b64cert'",
  "PrivateKeyAllowed": "Optional",
  "JobProperties": [
    {
      "Name": "DiscoverySuffix",
      "DisplayName": "Discovery Suffix",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "_pfx",
      "Required": false,
      "Description": "The secret-key-name suffix Discovery jobs use to identify candidate PFX certificate secrets. Defaults to '_pfx'."
    }
  ],
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required",
  "SupportedOperations": {
    "Add": true,
    "Create": true,
    "Discovery": true,
    "Enrollment": false,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "ServerUsername",
      "DisplayName": "Server Username",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true,
      "IsPAMEligible": true,
      "Description": "The base URI (and port) to the instance of Hashicorp Vault ex: https://localhost:8200"
    },
    {
      "Name": "ServerPassword",
      "DisplayName": "Server Password",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true,
      "Description": "Vault token that will be used by the Orchestrator integration for authenticating and performing operations in the Vault instance. Required unless 'Use OAuth 2.0 (Client Credentials)' is enabled."
    },
    {
      "Name": "UseOAuth",
      "DisplayName": "Use OAuth 2.0 (Client Credentials)",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": false,
      "Description": "Enables OAuth 2.0 Client Credentials authentication: the orchestrator obtains a JWT from the configured IdP (e.g. PingFederate, Microsoft Entra ID) and exchanges it for a short-lived Vault token via Vault's JWT auth method, instead of using a static 'Server Password' Vault token."
    },
    {
      "Name": "ClientId",
      "DisplayName": "Client ID",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true,
      "Description": "The OAuth 2.0 Client ID registered with your IdP. Only used when 'Use OAuth 2.0 (Client Credentials)' is enabled."
    },
    {
      "Name": "ClientSecret",
      "DisplayName": "Client Secret",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "IsPAMEligible": true,
      "Description": "The OAuth 2.0 Client Secret for the above Client ID. Only used when 'Use OAuth 2.0 (Client Credentials)' is enabled."
    },
    {
      "Name": "OAuthUrl",
      "DisplayName": "OAuth Token Endpoint",
      "Type": "String",
      "DependsOn": "UseOAuth",
      "DefaultValue": "",
      "Required": false,
      "Description": "The IdP's OAuth 2.0 token endpoint URL used to obtain a JWT via the Client Credentials grant. Only used when 'Use OAuth 2.0 (Client Credentials)' is enabled."
    },
    {
      "Name": "Scope",
      "DisplayName": "OAuth Scope",
      "Type": "String",
      "DependsOn": "UseOAuth",
      "DefaultValue": "",
      "Required": false,
      "Description": "Optional OAuth 2.0 scope to request from the IdP (e.g. Entra ID typically needs 'api://<app-id-uri>/.default'). Only used when 'Use OAuth 2.0 (Client Credentials)' is enabled."
    },
    {
      "Name": "VaultRoleName",
      "DisplayName": "Vault Role Name",
      "Type": "String",
      "DependsOn": "UseOAuth",
      "DefaultValue": "",
      "Required": false,
      "Description": "The name of the Vault role, configured under the JWT auth mount (e.g. 'auth/jwt/role/<name>'), to authenticate against using the JWT obtained from the IdP. Only used when 'Use OAuth 2.0 (Client Credentials)' is enabled."
    },
    {
      "Name": "AuthMountPoint",
      "DisplayName": "JWT Auth Mount Point",
      "Type": "String",
      "DependsOn": "UseOAuth",
      "DefaultValue": "jwt/",
      "Required": false,
      "Description": "The mount point of Vault's JWT auth method used to exchange the IdP-issued JWT for a Vault token. Only used when 'Use OAuth 2.0 (Client Credentials)' is enabled."
    },
    {
      "Name": "IncludeCertChain",
      "DisplayName": "Include Certificate Chain",
      "Description": "Should the certificate chain be included when performing an enrollment?",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": false
    },
    {
      "Name": "MountPoint",
      "DisplayName": "Mount Point",
      "Description": "The base mount point of the secrets engine.  If using Vault Namespaces, include the namespace; ie. <namespace>/<mount point>",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false
    },
    {
      "Name": "PassphrasePath",
      "DisplayName": "Passphrase Path",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "Description": "This is the path to the secret that contains the passphrase to the cert store file.  If empty or omitted, assume the secret is named 'passphrase' on the same level as the certificate store secret."
    }
  ],
  "EntryParameters": [],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default",
    "StorePassword": {
      "Description": "Vault token that will be used for authenticating",
      "IsPAMEligible": true
    }
  }
}'

