#!/bin/bash
# Store Type creation script using curl
# Generated by Doctool

set -e

# Configuration - set these variables before running
KEYFACTOR_HOSTNAME="${KEYFACTOR_HOSTNAME}"
KEYFACTOR_API_PATH="${KEYFACTOR_API_PATH:-KeyfactorAPI}"
KEYFACTOR_AUTH_TOKEN="${KEYFACTOR_AUTH_TOKEN}"

echo "Creating store type: HCVPKI"
curl -s -X POST "https://${KEYFACTOR_HOSTNAME}/${KEYFACTOR_API_PATH}/CertificateStoreTypes" \
  -H "Authorization: Bearer ${KEYFACTOR_AUTH_TOKEN}" \
  -H "Content-Type: application/json" \
  -H "x-keyfactor-requested-with: APIClient" \
  -d '{
  "Name": "Hashicorp Vault PKI",
  "ShortName": "HCVPKI",
  "Capability": "HCVPKI",
  "LocalStore": false,
  "JobProperties": [],
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "PrivateKeyAllowed": "Forbidden",
  "CustomAliasAllowed": "Forbidden",
  "StorePathType": "Fixed",
  "StorePathValue": "/",
  "SupportedOperations": {
    "Add": false,
    "Create": false,
    "Discovery": false,
    "Enrollment": false,
    "Remove": false
  },
  "Properties": [
    {
      "Name": "ServerUsername",
      "DisplayName": "Server Username",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true,
      "IsPAMEligible": true,
      "Description": "The base URI (and port) to the instance of Hashicorp Vault ex: https://localhost:8200"
    },
    {
      "Name": "ServerPassword",
      "DisplayName": "Server Password",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true,
      "IsPAMEligible": true,
      "Description": "Vault token that will be used by the Orchestrator integration for authenticating and performing operations in the Vault instance"
    },
    {
      "Name": "MountPoint",
      "DisplayName": "Mount Point",
      "Description": "This is the mount point of the instance of the PKI or Keyfactor secrets engine plugin.  If using enterprise namespaces: <namespace>/<mount point>",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true
    },
    {
      "Name": "PassphrasePath",
      "DisplayName": "Passphrase Path",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "Description": "This is the path to the secret that contains the passphrase to the cert store file.  If empty or omitted, assume the secret is named 'passphrase' on the same level as the certificate store secret."
    }
  ],
  "EntryParameters": [],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default",
    "StorePassword": {
      "Description": "Vault token that will be used for authenticating",
      "IsPAMEligible": true
    }
  }
}'

echo "Creating store type: HCVKVPEM"
curl -s -X POST "https://${KEYFACTOR_HOSTNAME}/${KEYFACTOR_API_PATH}/CertificateStoreTypes" \
  -H "Authorization: Bearer ${KEYFACTOR_AUTH_TOKEN}" \
  -H "Content-Type: application/json" \
  -H "x-keyfactor-requested-with: APIClient" \
  -d '{
  "Name": "Hashicorp Vault Key-Value PEM",
  "ShortName": "HCVKVPEM",
  "Capability": "HCVKVPEM",
  "LocalStore": false,
  "PrivateKeyAllowed": "Optional",
  "JobProperties": [],
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required",
  "SupportedOperations": {
    "Add": true,
    "Create": true,
    "Discovery": true,
    "Enrollment": false,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "ServerUsername",
      "DisplayName": "Server Username",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true,
      "IsPAMEligible": true,
      "Description": "The base URI (and port) to the instance of Hashicorp Vault ex: https://localhost:8200"
    },
    {
      "Name": "ServerPassword",
      "DisplayName": "Server Password",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true,
      "IsPAMEligible": true,
      "Description": "Vault token that will be used by the Orchestrator integration for authenticating and performing operations in the Vault instance"
    },
    {
      "Name": "SubfolderInventory",
      "DisplayName": "Subfolder Inventory",
      "Description": "Should certificates found in sub-paths be included when performing an inventory?",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": false
    },
    {
      "Name": "IncludeCertChain",
      "DisplayName": "Include Certificate Chain",
      "Description": "Should the certificate chain be included when performing an enrollment?",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": false
    },
    {
      "Name": "MountPoint",
      "DisplayName": "Mount Point",
      "Description": "The base mount point of the secrets engine.  If using Vault Namespaces, include the namespace; ie. <namespace>/<mount point>",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false
    }
  ],
  "EntryParameters": [],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default",
    "StorePassword": {
      "Description": "Vault token that will be used for authenticating",
      "IsPAMEligible": true
    }
  }
}'

echo "Creating store type: HCVKVJKS"
curl -s -X POST "https://${KEYFACTOR_HOSTNAME}/${KEYFACTOR_API_PATH}/CertificateStoreTypes" \
  -H "Authorization: Bearer ${KEYFACTOR_AUTH_TOKEN}" \
  -H "Content-Type: application/json" \
  -H "x-keyfactor-requested-with: APIClient" \
  -d '{
  "Name": "Hashicorp Vault Key-Value JKS",
  "ShortName": "HCVKVJKS",
  "Capability": "HCVKVJKS",
  "LocalStore": false,
  "StorePathType": "",
  "StorePathValue": "example: '/mycerts/certstore.jks?b64cert'",
  "PrivateKeyAllowed": "Optional",
  "JobProperties": [],
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required",
  "SupportedOperations": {
    "Add": true,
    "Create": true,
    "Discovery": true,
    "Enrollment": false,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "ServerUsername",
      "DisplayName": "Server Username",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true,
      "IsPAMEligible": true,
      "Description": "The base URI (and port) to the instance of Hashicorp Vault ex: https://localhost:8200"
    },
    {
      "Name": "ServerPassword",
      "DisplayName": "Server Password",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true,
      "IsPAMEligible": true,
      "Description": "Vault token that will be used by the Orchestrator integration for authenticating and performing operations in the Vault instance"
    },
    {
      "Name": "IncludeCertChain",
      "DisplayName": "Include Certificate Chain",
      "Description": "Should the certificate chain be included when performing an enrollment?",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": false
    },
    {
      "Name": "MountPoint",
      "DisplayName": "Mount Point",
      "Description": "The base mount point of the secrets engine.  If using Vault Namespaces, include the namespace; ie. <namespace>/<mount point>",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false
    },
    {
      "Name": "PassphrasePath",
      "DisplayName": "Passphrase Path",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "Description": "This is the path to the secret that contains the passphrase to the cert store file.  If empty or omitted, assume the secret is named 'passphrase' on the same level as the certificate store secret."
    }
  ],
  "EntryParameters": [],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default",
    "StorePassword": {
      "Description": "Vault token that will be used for authenticating",
      "IsPAMEligible": true
    }
  }
}'

echo "Creating store type: HCVKVP12"
curl -s -X POST "https://${KEYFACTOR_HOSTNAME}/${KEYFACTOR_API_PATH}/CertificateStoreTypes" \
  -H "Authorization: Bearer ${KEYFACTOR_AUTH_TOKEN}" \
  -H "Content-Type: application/json" \
  -H "x-keyfactor-requested-with: APIClient" \
  -d '{
  "Name": "Hashicorp Vault Key-Value PKCS12",
  "ShortName": "HCVKVP12",
  "Capability": "HCVKVP12",
  "LocalStore": false,
  "StorePathType": "",
  "StorePathValue": "example: '/mycerts/certstore.p12?b64cert'",
  "PrivateKeyAllowed": "Optional",
  "JobProperties": [],
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required",
  "SupportedOperations": {
    "Add": true,
    "Create": true,
    "Discovery": true,
    "Enrollment": false,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "ServerUsername",
      "DisplayName": "Server Username",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true,
      "IsPAMEligible": true,
      "Description": "The base URI (and port) to the instance of Hashicorp Vault ex: https://localhost:8200"
    },
    {
      "Name": "ServerPassword",
      "DisplayName": "Server Password",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true,
      "IsPAMEligible": true,
      "Description": "Vault token that will be used by the Orchestrator integration for authenticating and performing operations in the Vault instance"
    },
    {
      "Name": "IncludeCertChain",
      "DisplayName": "Include Certificate Chain",
      "Description": "Should the certificate chain be included when performing an enrollment?",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": false
    },
    {
      "Name": "MountPoint",
      "DisplayName": "Mount Point",
      "Description": "The base mount point of the secrets engine.  If using Vault Namespaces, include the namespace; ie. <namespace>/<mount point>",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false
    },
    {
      "Name": "PassphrasePath",
      "DisplayName": "Passphrase Path",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "Description": "This is the path to the secret that contains the passphrase to the cert store file.  If empty or omitted, assume the secret is named 'passphrase' on the same level as the certificate store secret."
    }
  ],
  "EntryParameters": [],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default",
    "StorePassword": {
      "Description": "Vault token that will be used for authenticating",
      "IsPAMEligible": true
    }
  }
}'

echo "Creating store type: HCVKVPFX"
curl -s -X POST "https://${KEYFACTOR_HOSTNAME}/${KEYFACTOR_API_PATH}/CertificateStoreTypes" \
  -H "Authorization: Bearer ${KEYFACTOR_AUTH_TOKEN}" \
  -H "Content-Type: application/json" \
  -H "x-keyfactor-requested-with: APIClient" \
  -d '{
  "Name": "Hashicorp Vault Key-Value PFX",
  "ShortName": "HCVKVPFX",
  "Capability": "HCVKVPFX",
  "LocalStore": false,
  "StorePathType": "",
  "StorePathValue": "example: '/mycerts/certstore.pfx?b64cert'",
  "PrivateKeyAllowed": "Optional",
  "JobProperties": [],
  "ServerRequired": true,
  "PowerShell": false,
  "BlueprintAllowed": false,
  "CustomAliasAllowed": "Required",
  "SupportedOperations": {
    "Add": true,
    "Create": true,
    "Discovery": true,
    "Enrollment": false,
    "Remove": true
  },
  "Properties": [
    {
      "Name": "ServerUsername",
      "DisplayName": "Server Username",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true,
      "IsPAMEligible": true,
      "Description": "The base URI (and port) to the instance of Hashicorp Vault ex: https://localhost:8200"
    },
    {
      "Name": "ServerPassword",
      "DisplayName": "Server Password",
      "Type": "Secret",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": true,
      "IsPAMEligible": true,
      "Description": "Vault token that will be used by the Orchestrator integration for authenticating and performing operations in the Vault instance"
    },
    {
      "Name": "IncludeCertChain",
      "DisplayName": "Include Certificate Chain",
      "Description": "Should the certificate chain be included when performing an enrollment?",
      "Type": "Bool",
      "DependsOn": "",
      "DefaultValue": "false",
      "Required": false
    },
    {
      "Name": "MountPoint",
      "DisplayName": "Mount Point",
      "Description": "The base mount point of the secrets engine.  If using Vault Namespaces, include the namespace; ie. <namespace>/<mount point>",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false
    },
    {
      "Name": "PassphrasePath",
      "DisplayName": "Passphrase Path",
      "Type": "String",
      "DependsOn": "",
      "DefaultValue": "",
      "Required": false,
      "Description": "This is the path to the secret that contains the passphrase to the cert store file.  If empty or omitted, assume the secret is named 'passphrase' on the same level as the certificate store secret."
    }
  ],
  "EntryParameters": [],
  "PasswordOptions": {
    "EntrySupported": false,
    "StoreRequired": false,
    "Style": "Default",
    "StorePassword": {
      "Description": "Vault token that will be used for authenticating",
      "IsPAMEligible": true
    }
  }
}'

