#!/bin/bash
# Store Type creation script using kfutil
# Generated by Doctool

set -e

echo "Creating store type: HCVPKI"
kfutil store-types create HCVPKI

echo "Creating store type: HCVKVPEM"
kfutil store-types create HCVKVPEM

echo "Creating store type: HCVKVJKS"
kfutil store-types create HCVKVJKS

echo "Creating store type: HCVKVP12"
kfutil store-types create HCVKVP12

echo "Creating store type: HCVKVPFX"
kfutil store-types create HCVKVPFX

